version: '3'
services:
  top.api:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:19.4.0-alpine
    container_name: top-api
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./.env:/opt/app/.env
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.4
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mmmihaeel
      - MONGO_INITDB_ROOT_PASSWORD=dgs-fhhhhxc_htgf&fdhgNMfdsg
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data-4.4:/data/db
    command: --wiredTigerCacheSizeGB 1.5